import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Packages',
      items: [
        'packages/README',
        {
          type: 'category',
          label: 'NPM Packages',
          items: [{type: 'autogenerated', dirName: 'packages/npm-packages'}],
        },
        {
          type: 'category',
          label: 'Composer Packages',
          items: [{type: 'autogenerated', dirName: 'packages/composer-packages'}],
        },
      ],
    },
  ],
};

export default sidebars;
